name: TntRun
version: 1.0.0
api: 4.0.0
author: ItsToxicGG
main: Toxic\TntRun

permissions:
  tntrun.command:
    default: op
    description: Permission to all tntrun commands 
  tntrun.nonop:
    default: true
    description: Permission to normal Players Commands
